# Generated by Django 2.2.19 on 2021-04-10 21:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCursoAtividadeComplementar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('categoria_atividade_complementar', models.ManyToManyField(to='aplic.CategoriaCurso')),
            ],
            options={
                'verbose_name': 'Categoria Curso Atividade Complementar',
                'verbose_name_plural': 'Categoria Curso Atividade Complementar',
            },
        ),
        migrations.AddField(
            model_name='atividadecomplementar',
            name='justificativa',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='justificativa'),
        ),
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.CategoriaCursoAtividadeComplementar'),
        ),
    ]
