# Generated by Django 2.2.19 on 2021-04-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadecomplementar',
            name='justificativa',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='justificativa'),
        ),
    ]
