# Generated by Django 2.2.19 on 2021-04-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='publishing_company',
            field=models.CharField(max_length=255, verbose_name='Editora'),
        ),
    ]
