# Generated by Django 2.2.19 on 2021-04-04 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_atividadecomplementar_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadecomplementar',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Aluno'),
        ),
    ]
