# Generated by Django 2.2.19 on 2021-04-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_auto_20210410_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.CategoriaAtividadeComplementar'),
        ),
    ]
