# Generated by Django 2.2.19 on 2021-04-10 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_auto_20210405_0224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livro',
        ),
        migrations.AlterField(
            model_name='campus',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='campus', to='aplic.Instituicao'),
        ),
    ]
