# Generated by Django 2.2.19 on 2021-04-10 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_remove_atividadecomplementar_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj', models.IntegerField(primary_key=True, serialize=False, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=155, null=True, verbose_name='Nome Fantasia')),
                ('telefone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AddField(
            model_name='atividadecomplementar',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.CategoriaAtividadeComplementar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Empresa'),
        ),
    ]
